Repository connection-2023/frontend, pull requests merged in 2023-11, with the labels that each got.

#123 클래스 상세페이지 반응형 추가 구현
  public/icons/download.svg
  public/icons/svg.ts
  src/app/class/[id]/_components/ClassReviewSection.tsx
  src/app/class/[id]/_components/DiscountCouponBanner.tsx
  src/app/class/[id]/_components/ResponsiveApply.tsx
  src/app/class/[id]/page.tsx
  src/components/Calendar/ScheduleCalendar.tsx
  src/components/ClassNotice/Notice.tsx
  src/components/ScheduleView/ScheduleView.tsx
Labels: feat

#119 feat(#115): 알림 페이지 구현
  public/icons/delete.svg
  public/icons/readMessage.svg
  public/icons/svg.ts
  public/icons/unreadMessage.svg
  src/app/notify/layout.tsx
  src/app/notify/page.tsx
  src/constants/dummy.ts
  src/types/types.d.ts
Labels: feat

#127 feat/#124 대시보드 페이지 구현
  public/icons/classStatus.svg
  public/icons/recent.svg
  public/icons/review.svg
  public/icons/svg.ts
  src/app/_components/Sidebar.tsx
  src/app/dashboard/_components/RecentApply.tsx
  src/app/dashboard/_components/RecentReview.tsx
  src/app/dashboard/_components/ResponsiveScheduleView.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/my/layout.tsx
  src/components/Calendar/DashboardCalendar.tsx
  src/components/Calendar/DayCalendar.tsx
  src/store/dashboardStore.ts
  src/store/index.ts
  src/styles/calendar.css
  src/utils/fullCalendarUtils.ts
Labels: feat

#130 feat/#129-결제 완료 페이지 및 영수증 모달(컴포넌트) 구현
  .vscode/settings.json
  public/icons/applySuccess.svg
  public/icons/svg.ts
  public/icons/wavyLine.svg
  public/images/receipt-background.svg
  src/app/class/[id]/_components/ClassReviewSection.tsx
  src/app/class/apply-complete/@modal/(.)receipt/page.tsx
  src/app/class/apply-complete/@modal/default.tsx
  src/app/class/apply-complete/layout.tsx
  src/app/class/apply-complete/page.tsx
  src/app/class/apply-complete/receipt/page.tsx
  src/app/layout.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ReceiptModal.tsx
  tailwind.config.ts
Labels: feat

#132 클래스 상세 조회 및 클래스 신청 페이지 api 연동 (쿠폰 제외)
  package-lock.json
  package.json
  src/app/api/payment/confirm/route.ts
  src/app/api/payment/payInfo/route.ts
  src/app/api/post/class/route.ts
  src/app/class/[id]/_components/Apply.tsx
  src/app/class/[id]/_components/ClassReviewSection.tsx
  src/app/class/[id]/_components/ProfileButtons.tsx
  src/app/class/[id]/_components/ResponsiveApply.tsx
  src/app/class/[id]/_components/apply/ReservationItem.tsx
  src/app/class/[id]/_components/apply/SelectBox.tsx
  src/app/class/[id]/page.tsx
  src/app/class/apply/[id]/_components/ApplyClassList.tsx
  src/app/class/apply/[id]/_components/ApplySidebar.tsx
  src/app/class/apply/[id]/_components/PaymentType.tsx
  src/app/class/apply/[id]/_components/ReservationInfo.tsx
  src/app/class/apply/[id]/page.tsx
  src/components/Calendar/ScheduleCalendar.tsx
  src/components/ScheduleView/ScheduleView.tsx
  src/lib/apis/classApis.ts
  src/lib/apis/paymentApis.ts
  src/store/index.ts
  src/store/paymentStore.ts
  src/types/auth.d.ts
  src/types/class.d.ts
  src/types/payment.d.ts
  src/utils/parseUtils.ts
Labels: feat, API

#140 [refactor/feat] 강사 프로필 처리 추가 및 토큰 로직 리팩토링
  src/app/_components/Header/ProfileMenu.tsx
  src/app/api/auth/switch-user/route.ts
  src/app/api/instructors/myProfile/route.ts
  src/app/api/users/me/route.ts
  src/lib/apis/userApi.ts
  src/lib/useSession.tsx
  src/utils/switchUserUtil.ts
Labels: feat, refactor

#143 refactor/#142 calendar
  src/app/class/create/_components/ClassSchedule/ClassDay/SpecificDate.tsx
  src/app/class/create/_components/ClassSchedule/ClassRange/ClassRange.tsx
  src/app/class/create/_components/ClassSchedule/DayOff/DayOff.tsx
  src/app/dashboard/page.tsx
  src/app/my/income/_components/IncomeRange.tsx
  src/app/my/income/_components/PaymentRange.tsx
  src/app/my/manage/myclass/_components/detail/EditDayOff.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/components/Calendar/DashboardCalendar.tsx
  src/components/Calendar/DayOffCalendar.tsx
  src/components/Calendar/IncomeCalendar.tsx
  src/components/Calendar/InputClassDates.tsx
  src/components/Calendar/RangeCalendar.tsx
  src/components/Calendar/ScheduleCalendar.tsx
  src/components/Calendar/SingleCalendar.stories.tsx
  src/components/Calendar/SingleCalendar.tsx
  src/components/ClassPreview/ClassDates.tsx
  src/components/ClassPreview/ClassPreview.tsx
  src/components/ScheduleView/ScheduleView.tsx
  src/utils/calendarUtils/CalendarCaption.tsx
  src/utils/calendarUtils/dateUtils.ts
Labels: refactor

#145 Feat/refactor#126 클래스 작성 페이지 api 연결 및 기능 구현
  public/icons/svg.ts
  public/icons/trashcan.svg
  src/app/Instructor/apply/_components/InstructorIntroduction.tsx
  src/app/Instructor/apply/page.tsx
  src/app/api/class/create/route.ts
  src/app/api/class/drafts/createDraft/route.ts
  src/app/api/class/drafts/deleteDraft/route.ts
  src/app/api/class/drafts/getDraft/route.ts
  src/app/api/class/drafts/getDrafts/route.ts
  src/app/api/class/drafts/updateDraft/route.ts
  src/app/api/image/delete/route.ts
  src/app/class/create/_components/ClassCategory.tsx
  src/app/class/create/_components/ClassCategory/CategoryContainer.tsx
  src/app/class/create/_components/ClassCategory/ClassSizeSelect.tsx
  src/app/class/create/_components/ClassCategory/RadioComponent.tsx
  src/app/class/create/_components/ClassCreate.tsx
  src/app/class/create/_components/ClassExplanation.tsx
  src/app/class/create/_components/ClassLocation.tsx
  src/app/class/create/_components/ClassLocation/ConfirmedLocation.tsx
  src/app/class/create/_components/ClassPrice.tsx
  src/app/class/create/_components/ClassPrice/AppliedCouponDisplay.tsx
  src/app/class/create/_components/ClassPrice/ClassInfo.tsx
  src/app/class/create/_components/ClassSchedule.tsx
  src/app/class/create/_components/ClassSchedule/ClassRange/ClassRange.tsx
  src/app/class/create/_components/ClassSchedule/DayOff/DayOff.tsx
  src/app/class/create/_components/ClassStoreInitializer.tsx
  src/app/class/create/_components/DraftListModal.tsx
  src/app/class/create/_components/DraftListModalContainer.tsx
  src/app/class/create/address/_components/Address.tsx
  src/app/class/create/address/page.tsx
  src/app/class/create/page.tsx
  src/components/GenreCheckboxGroup/GenreCheckboxGroup.tsx
  src/components/Map/Map.tsx
  src/components/ScheduleView/ScheduleView.tsx
  src/components/SelectLocation/CityList.tsx
  src/components/SelectLocation/SelectLocation.tsx
  src/components/TextArea/CustomEditor.tsx
  src/components/TextArea/TextAreaSection.tsx
  src/components/UploadImage/UploadImage.tsx
  src/constants/administrativeDistrict.ts
  src/lib/apis/classApi.ts
  src/lib/apis/imageApi.ts
  src/lib/apis/instructorApi.ts
  src/lib/apis/searchAddress.ts
  src/lib/apis/serverApis/classApi.ts
  src/store/classCreate.ts
  src/types/address.d.ts
  src/types/class.d.ts
  src/types/instructor.d.ts
  src/utils/apiDataPreparers.ts
  src/utils/apiDataProcessor.ts
Labels: feat, refactor, API

#152 Feat/refactor#148 Refresh토큰 연결 & 네이버 로그인 & 헤더 컴포넌트 리팩토링
  next.config.js
  public/icons/smallLogo.svg
  src/app/(auth)/login/_components/LoginButtons.tsx
  src/app/(auth)/login/_components/NaverAuth.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/HeaderMenu.tsx
  src/app/_components/Header/Profile.tsx
  src/app/_components/Header/ProfileMenu.tsx
  src/app/_components/Header/UserProfileLinks.tsx
  src/app/_components/Header/UserStoreInitializer.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/naver-login/route.ts
  src/app/api/auth/refresh/route.ts
  src/app/api/auth/switch-user/route.ts
  src/app/layout.tsx
  src/app/my/layout.tsx
  src/app/page.tsx
  src/constants/constants.ts
  src/lib/apis/instructorApi.ts
  src/lib/apis/serverApis/userApi.ts
  src/lib/apis/userApi.ts
  src/lib/useSession.tsx
  src/middleware.ts
  src/store/scrollStore.ts
Labels: feat, refactor, API

#150 클래스 등록 일정 및 공지사항 파트 API 및 hook-form 연결
  src/app/class/create/_components/ClassCreate.tsx
  src/app/class/create/_components/ClassSchedule.tsx
  src/app/class/create/_components/ClassSchedule/ClassDay/ClassDay.tsx
  src/app/class/create/_components/ClassSchedule/ClassDay/DayByDay.tsx
  src/app/class/create/_components/ClassSchedule/ClassDay/SpecificDate.tsx
  src/app/class/create/_components/ClassSchedule/ClassDay/TimeList.tsx
  src/app/class/create/_components/ClassSchedule/ClassRange/ClassRange.tsx
  src/app/class/create/_components/ClassSchedule/DayOff/DayOff.tsx
  src/app/class/create/layout.tsx
  src/components/Calendar/InputClassDates.tsx
  src/components/Calendar/RangeCalendar.tsx
  src/components/Calendar/SingleCalendar.tsx
  src/components/ScheduleView/ScheduleView.tsx
  src/recoil/ClassSchedule/atoms.ts
  src/store/classCreate.ts
  src/store/classScheduleStore.ts
  src/store/index.ts
  src/types/class.d.ts
  src/utils/apiDataProcessor.ts
  src/utils/calendarUtils/dateUtils.ts
  src/utils/specificDateReducer.ts
Labels: feat, refactor, API

#151 Feat/#93 my payment
  src/app/_components/Sidebar.tsx
  src/app/my/payment-history/_components/PaymentList.tsx
  src/app/my/payment-history/page.tsx
  src/types/types.d.ts
Labels: feat

#154 홈화면 반응형 구현
  src/app/_components/Banner.tsx
  src/app/_components/CarouselTemplate.tsx
  src/app/_components/Footer.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ClassPreview/ClassPreview.tsx
  src/components/ClassPreview/ResponsiveClassPreview.tsx
  src/components/Preview/InstructorPreview.tsx
  src/components/Preview/SuggestionPreview.tsx
  tailwind.config.ts
Labels: feat

#158 Feat/#155 mypage header
  public/icons/hamburgerMenu.svg
  public/icons/heart.svg
  public/icons/svg.ts
  src/app/_components/Header/HeaderMenu.tsx
  src/app/_components/Sidebar.tsx
  src/app/my/class/_components/ClassDetailView.tsx
  src/app/my/class/_components/ClassList.tsx
  src/app/my/class/_components/ClassListView.tsx
  src/app/my/class/page.tsx
  src/app/my/layout.tsx
  src/app/my/manage/schedule/page.tsx
  src/components/Like/Like.tsx
  src/components/Modal/SidebarModal.tsx
Labels: feat

#162 클래스 및 결제 페이지 API 연동
  public/icons/alarm.svg
  public/icons/applySuccess.svg
  src/app/Instructor/[id]/page.tsx
  src/app/_components/Header/UserProfileLinks.tsx
  src/app/api/class/likes/add/route.ts
  src/app/api/class/likes/delete/route.ts
  src/app/api/payment/cancel/route.ts
  src/app/api/payment/history/route.ts
  src/app/api/post/class/review/route.ts
  src/app/api/post/review/likes/add/route.ts
  src/app/api/post/review/likes/delete/route.ts
  src/app/class/[id]/_components/ClassReviewSection.tsx
  src/app/class/[id]/_components/OptionButton.tsx
  src/app/class/[id]/_components/UserReservation.tsx
  src/app/class/[id]/layout.tsx
  src/app/class/[id]/page.tsx
  src/app/class/apply-complete/@modal/(.)receipt/page.tsx
  src/app/class/apply-complete/page.tsx
  src/app/class/apply-complete/receipt/page.tsx
  src/app/class/apply/[id]/_components/ApplySidebar.tsx
  src/app/class/apply/[id]/page.tsx
  src/components/Like/Like.tsx
  src/components/Review/UserReview.tsx
  src/lib/apis/classApis.ts
  src/lib/apis/paymentApis.ts
  src/lib/apis/serverApis/classPostApis.ts
  src/lib/apis/serverApis/paymentsApis.ts
  src/types/class.d.ts
  src/types/payment.d.ts
Labels: feat, API
