Repository connection-2023/frontend, pull requests merged in 2023-10, with the labels that each got.

#77 Feat/#62 header component
  public/icons/alarm.svg
  public/icons/comment.svg
  public/icons/map.svg
  public/icons/search.svg
  public/icons/svg.ts
  public/icons/transform.svg
  src/app/layout.tsx
  src/components/Header.tsx/Header.tsx
  src/components/Header.tsx/HeaderMenu.tsx
  src/components/Header.tsx/Profile.tsx
  src/components/Header.tsx/ProfileMenu.tsx
  src/components/Header.tsx/UserProfileLinks.tsx
  src/constants/constants.ts
  src/constants/dummy.ts
Labels: feat

#71 Feat/#70 carousel refactor
  src/app/_components/CarouselTemplate.tsx
  src/components/Carousel/Carousel.test.tsx
  src/components/Carousel/Carousel.tsx
Labels: refactor

#78 Feat/#76 manage plan
  package-lock.json
  package.json
  public/icons/calendarDetail.svg
  public/icons/svg.ts
  src/app/manage/schedule/_components/CalendarDetail.tsx
  src/app/manage/schedule/_components/Event.tsx
  src/app/manage/schedule/_components/FullCalendar.tsx
  src/app/manage/schedule/_components/ToolBar.tsx
  src/app/manage/schedule/page.tsx
  src/styles/fullCalendar.css
  src/types/types.d.ts
  src/utils/fullCalendarUtils.ts
Labels: feat

#80 Feat/#79 manage sidebar
  public/icons/ArrowUp.svg
  src/app/manage/schedule/page.tsx
  src/app/my/_components/Sidebar.tsx
  src/app/my/layout.tsx
  src/app/my/manage/schedule/_components/CalendarDetail.tsx
  src/app/my/manage/schedule/_components/Event.tsx
  src/app/my/manage/schedule/_components/FullCalendar.tsx
  src/app/my/manage/schedule/_components/ToolBar.tsx
  src/app/my/manage/schedule/page.tsx
  src/components/Filter/FilterModal.tsx
Labels: feat

#83 Feat/#82 instructor myclass
  public/icons/ArrowRight.svg
  public/icons/comment.svg
  public/icons/edit.svg
  public/icons/svg.ts
  src/app/class/[id]/page.tsx
  src/app/class/create/page.tsx
  src/app/my/manage/myclass/_components/ClassDetailView.tsx
  src/app/my/manage/myclass/_components/ClassList.tsx
  src/app/my/manage/myclass/_components/ClassListView.tsx
  src/app/my/manage/myclass/_components/detail/ClassOverview.tsx
  src/app/my/manage/myclass/_components/detail/ClassTable.tsx
  src/app/my/manage/myclass/_components/detail/EditDayOff.tsx
  src/app/my/manage/myclass/_components/detail/EnrollmentModal.tsx
  src/app/my/manage/myclass/page.tsx
  src/app/my/manage/schedule/_components/ToolBar.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/components/ClassNotice/Notice.tsx
  src/components/Header.tsx/UserProfileLinks.tsx
  src/constants/dummy.ts
  src/styles/globals.css
Labels: feat

#89 Feat/#88 report history
  public/icons/note.svg
  public/icons/svg.ts
  src/app/my/report/ReportModal.tsx
  src/app/my/report/page.tsx
  src/types/types.d.ts
Labels: feat

#91 Feat/#85 apply instructor
  src/app/Instructor/apply/_components/InstructorAuth.tsx
  src/app/Instructor/apply/layout.tsx
  src/app/Instructor/apply/page.tsx
Labels: feat

#92 Feat/#90 income
  package-lock.json
  package.json
  public/icons/bigArrow.svg
  public/icons/bill.svg
  public/icons/doubleRight.svg
  public/icons/excel.svg
  public/icons/money.svg
  public/icons/svg.ts
  src/app/my/income/_components/AccountInfo.tsx
  src/app/my/income/_components/IncomeDataViewer.tsx
  src/app/my/income/_components/IncomeOverview.tsx
  src/app/my/income/_components/IncomeRange.tsx
  src/app/my/income/_components/IncomeTable.tsx
  src/app/my/income/_components/Payment.tsx
  src/app/my/income/page.tsx
  src/components/Calendar/IncomeCalendar.tsx
  src/constants/dummy.ts
  src/types/types.d.ts
  src/utils/chartUtils.ts
Labels: feat

#99 Feat/#86 apply instructor profile
  src/app/Instructor/apply/_components/InstructorIntroduction.tsx
  src/app/Instructor/apply/layout.tsx
  src/app/Instructor/apply/page.tsx
  src/app/class/create/_components/ClassCategory.tsx
  src/app/class/create/_components/ClassLocation.tsx
  src/components/GenreCheckboxGroup/GenreCheckboxGroup.tsx
  src/components/GenreCheckboxGroup/GenreList.tsx
  src/components/GenreCheckboxGroup/GenreListAddition.tsx
  src/components/SelectLocation/SelectLocation.tsx
  src/components/TextArea/CustomEditor.tsx
  src/components/UploadImage/UploadImage.test.tsx
  src/components/UploadImage/UploadImage.tsx
  src/constants/constants.ts
  src/recoil/Create/atoms.ts
Labels: feat

#103 Feat/#102 my interest instructor
  .eslintrc.json
  src/app/_components/Header/Header.tsx
  src/app/my/_components/Sidebar.tsx
  src/app/my/instructor/_components/BlockedInstructors.tsx
  src/app/my/instructor/_components/InterestedInstructors.tsx
  src/app/my/instructor/page.tsx
  src/components/InstructorCard/InstructorCard.tsx
  src/constants/dummy.ts
  src/types/types.d.ts
Labels: feat

#104 Feat/#96 apply class
  next.config.js
  public/icons/musicalNote.svg
  public/icons/notice.svg
  public/icons/svg.ts
  src/app/class/apply/[id]/_components/ApplyClassList.tsx
  src/app/class/apply/[id]/_components/ApplySidebar.tsx
  src/app/class/apply/[id]/layout.tsx
  src/app/class/apply/[id]/page.tsx
  src/components/ClassNotice/Notice.tsx
  src/components/Header.tsx/Auth/ProfileSetup.tsx
  src/components/TextArea/TextAreaSection.tsx
  src/types/auth.d.ts
  src/types/types.d.ts
Labels: feat

#107 회원가입/로그인 api연결 및 로직 추가
  next.config.js
  package-lock.json
  package.json
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/register/route.ts
  src/app/api/auth/route.ts
  src/app/api/check-nickname/route.ts
  src/app/api/users/me/route.ts
  src/app/api/users/upload-profile/route.ts
  src/app/layout.tsx
  src/app/my/layout.tsx
  src/components/Header/Auth/AuthHome.tsx
  src/components/Header/Auth/AuthModal.tsx
  src/components/Header/Auth/ProfileSetup.tsx
  src/components/Header/Auth/SignUp.tsx
  src/components/Header/Profile.tsx
  src/components/Header/ProfileMenu.tsx
  src/components/Header/UserProfileLinks.tsx
  src/lib/apis/userApi.ts
  src/lib/useSession.tsx
  src/middleware.ts
  src/store/index.ts
  src/types/auth.d.ts
Labels: feat

#109 feat(#108): 관리페이지 변경된 디자인 적용
  public/icons/ArrowUp.svg
  public/icons/bookmark.svg
  public/icons/dashboard.svg
  public/icons/notFound.svg
  public/icons/report.svg
  public/icons/svg.ts
  src/app/my/_components/Sidebar.tsx
  src/app/my/income/_components/AccountInfo.tsx
  src/app/my/income/_components/IncomeDataViewer.tsx
  src/app/my/income/_components/IncomeOverview.tsx
  src/app/my/income/_components/IncomeTable.tsx
  src/app/my/income/_components/Payment.tsx
  src/app/my/income/_components/PaymentRange.tsx
  src/app/my/income/page.tsx
  src/app/my/layout.tsx
  src/app/my/manage/myclass/_components/ClassDetailView.tsx
  src/app/my/manage/myclass/_components/ClassList.tsx
  src/app/my/manage/myclass/_components/ClassListView.tsx
  src/app/my/manage/myclass/_components/detail/ClassOverview.tsx
  src/app/my/manage/myclass/_components/detail/EditDayOff.tsx
  src/app/my/manage/myclass/page.tsx
  src/app/my/manage/schedule/page.tsx
  src/app/my/report/page.tsx
  src/components/Filter/FilterModal.tsx
  tailwind.config.ts
Labels: feat

#117 classCard 컴포넌트 반응형 추가 구현 및 이름 변경
  src/app/Instructor/[id]/_components/ClassList.tsx
  src/app/page.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/ClassPreview/ClassDates.tsx
  src/components/ClassPreview/ClassPreview.stories.tsx
  src/components/ClassPreview/ClassPreview.tsx
  src/components/ClassPreview/ResponsiveClassPreview.tsx
Labels: feat, refactor

#118 feat(#112) 강사 상세 페이지 api 연결
  .eslintrc.json
  package-lock.json
  package.json
  src/app/Instructor/[id]/page.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/register/route.ts
  src/app/api/auth/switch-user/route.ts
  src/app/api/check-nickname/route.ts
  src/app/api/instructors/myProfile/route.ts
  src/app/api/post/instructor/route.ts
  src/app/api/users/me/route.ts
  src/app/api/users/upload-profile/route.ts
  src/app/my/_components/Sidebar.tsx
  src/app/my/manage/myclass/_components/ClassListView.tsx
  src/components/Header/Auth/AuthHome.tsx
  src/components/Header/Auth/UserInfoSetup.tsx
  src/components/Header/Profile.tsx
  src/components/Header/ProfileMenu.tsx
  src/components/Header/UserProfileLinks.tsx
  src/lib/apis/instructorApi.ts
  src/lib/apis/instructorPostApis.ts
  src/lib/apis/userApi.ts
  src/store/index.ts
  src/types/auth.d.ts
  src/types/instructor.d.ts
  src/types/types.d.ts
  src/utils/parseUtils.ts
  src/utils/sanitizeHtmlString.ts
Labels: feat, API
