Repository connection-2023/frontend, pull requests merged in 2023-09, with the labels that each got.

#5 Package/#4 prettier plugin tailwindcss 설치 및 세팅, eslint 수정
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  test/test.tsx
Labels: package

#7 package: autoprefixer 설치 및 세팅
  package-lock.json
  package.json
Labels: package

#23 Feat/#3 Carousel component
  public/icons/arrow.svg
  public/icons/svg.ts
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/Carousel.test.tsx
  src/components/Carousel/Carousel.tsx
Labels: feat

#22 Feat/#14 filter review
  .storybook/main.ts
  package-lock.json
  package.json
  public/favicon.ico
  public/icons/ArrowDown.svg
  public/icons/ArrowUp.svg
  public/icons/reset.svg
  public/icons/star.svg
  public/icons/svg.ts
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Calendar/Calendar.test.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/DisplayCalendar.stories.tsx
  src/components/Calendar/DisplayCalendar.tsx
  src/components/Calendar/InteractionCalendar.stories.tsx
  src/components/Calendar/InteractionCalendar.tsx
  src/components/Calendar/displayCalendar.css
  src/components/Calendar/interactionCalendar.css
  src/components/Calendar/tileClassName.ts
  src/components/ClassCard/Date.tsx
  src/components/Filter/DateFilter.tsx
  src/components/Filter/FilterButton.stories.tsx
  src/components/Filter/FilterButton.tsx
  src/components/Filter/PriceFilter.tsx
  src/components/Filter/ReviewFilter.tsx
  src/components/Review/Rating.stories.tsx
  src/components/Review/Rating.tsx
  src/components/Review/Review.tsx
  src/constants/constants.ts
  src/styles/calendar.css
Labels: feat

#27 Feat/#3 card img component
  src/components/Carousel/Carousel.tsx
  src/components/InstructorCard/ImagesViewer.tsx
  src/components/InstructorCard/InstructorCard.stories.tsx
  src/components/InstructorCard/InstructorCard.test.tsx
  src/components/InstructorCard/InstructorCard.tsx
Labels: feat

#28 Feat/#25 search page
  public/icons/clear.svg
  public/icons/close.svg
  public/icons/search.svg
  public/icons/svg.ts
  src/app/search/Close.tsx
  src/app/search/ListItem.tsx
  src/app/search/MyKeyword.tsx
  src/app/search/SearchInput.tsx
  src/app/search/layout.tsx
  src/app/search/page.tsx
Labels: feat

#30 Feat/#19 progress method selector component
  src/components/Filter/FilterButton.stories.tsx
  src/components/Filter/ProgressMethodFilter.tsx
  src/constants/constants.ts
Labels: feat

#32 Feat/#18 genre component
  src/components/Filter/FilterButton.stories.tsx
  src/components/Filter/GenreFilter.tsx
  src/constants/constants.ts
Labels: feat

#35 Feat/#31 map component
  .gitignore
  package-lock.json
  package.json
  src/components/Map/Map.stories.tsx
  src/components/Map/Map.test.tsx
  src/components/Map/Map.tsx
  src/constants/constants.ts
  src/styles/mapInfowindow.css
Labels: feat

#37 Feat/#20 date time component
  src/components/Filter/DateTimeFilter.tsx
  src/components/Filter/FilterButton.stories.tsx
  src/components/Filter/RegionFilter.tsx
  src/constants/constants.ts
Labels: feat

#36 Refactor/#34 calendar
  package-lock.json
  package.json
  public/icons/ArrowRight.svg
  public/icons/svg.ts
  src/app/class/[id]/_components/Schedule.tsx
  src/components/Calendar/BasicCalendar.stories.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/components/Calendar/Calendar.test.tsx
  src/components/Calendar/DisplayCalendar.stories.tsx
  src/components/Calendar/DisplayCalendar.tsx
  src/components/Calendar/InteractionCalendar.stories.tsx
  src/components/Calendar/InteractionCalendar.tsx
  src/components/Calendar/ScheduleCalendar.stories.tsx
  src/components/Calendar/ScheduleCalendar.tsx
  src/components/Calendar/displayCalendar.css
  src/components/Calendar/interactionCalendar.css
  src/components/Calendar/tileClassName.ts
  src/components/ClassCard/ClassCard.test.tsx
  src/components/ClassCard/Date.tsx
  src/components/Filter/DateFilter.tsx
  src/constants/constants.ts
  src/styles/calendar.css
Labels: refactor

#39 Feat/#38 carousel put
  next.config.js
  src/app/class/[id]/page.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/ClassCard/ClassCard.stories.tsx
  src/components/ClassCard/ClassCard.tsx
  src/constants/dummy.ts
  src/types/class.d.ts
Labels: feat

#41 Feat/#40 carousel component update
  src/app/class/[id]/page.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/Carousel.tsx
Labels: refactor

#51 feat(#50): class 생성 페이지 레이아웃 및 진행 바 구현
  src/app/class/create/layout.tsx
  src/app/class/create/page.tsx
Labels: feat

#54 Feat/#53 class create hook form recoil
  package-lock.json
  package.json
  src/app/class/create/_recoil/RecoilProvider.tsx
  src/app/class/create/_recoil/hookForm/HookForm.tsx
  src/app/class/create/_recoil/hookForm/atom.ts
  src/app/class/create/layout.tsx
  src/app/class/create/page.tsx
Labels: feat

#52 Feat/#42 instructor detail page
  .storybook/main.ts
  public/icons/instagram.svg
  public/icons/link.svg
  public/icons/option.svg
  public/icons/share.svg
  public/icons/svg.ts
  public/icons/youtube.svg
  src/app/Instructor/[id]/_components/ClassList.tsx
  src/app/Instructor/[id]/_components/InstructorCarousel.tsx
  src/app/Instructor/[id]/_components/ManagementButton.tsx
  src/app/Instructor/[id]/layout.tsx
  src/app/Instructor/[id]/page.tsx
  src/app/class/[id]/page.tsx
  src/components/Carousel/Carousel.tsx
  src/constants/constants.ts
  src/constants/dummy.ts
Labels: feat

#55 Feat/#45 class create image
  public/icons/UploadImg.svg
  public/icons/clear.svg
  public/icons/svg.ts
  src/app/search/_components/SearchInput.tsx
  src/components/UploadImage/UploadImage.tsx
Labels: feat

#57 Feat/#45 class create image
  package-lock.json
  package.json
  public/icons/crop.svg
  public/icons/svg.ts
  public/icons/zoomIn.svg
  public/icons/zoomOut.svg
  src/components/UploadImage/CropperModal.tsx
  src/components/UploadImage/UploadImage.test.tsx
  src/components/UploadImage/UploadImage.tsx
  src/styles/cropper.css
Labels: feat

#58 feat(#42): 인스타그램 퍼블리싱
  src/app/Instructor/[id]/page.tsx
  src/constants/dummy.ts
Labels: feat

#64 feat/#61-user main page
  public/icons/connectionLogo.svg
  public/icons/mainPopular.svg
  public/icons/mainTop.svg
  public/icons/smallLogo.svg
  public/icons/svg.ts
  public/images/banner.png
  src/app/_components/Banner.tsx
  src/app/_components/CarouselTemplate.tsx
  src/app/_components/Footer.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Preview/InstructorPreview.tsx
  src/components/Preview/SuggestionPreview.tsx
  src/constants/dummy.ts
Labels: feat

#67 Feat/#47 class create detail explanation
  package-lock.json
  package.json
  src/app/class/create/_components/ClassExplanation.tsx
  src/app/class/create/_components/ClassExplanation/CurriculumSection.tsx
  src/app/class/create/_components/ClassExplanation/TextAreaSection.tsx
  src/constants/constants.ts
  src/utils/useTextInput.tsx
Labels: feat

#69 Feat/#68 class create validation
  src/app/class/create/page.tsx
  src/components/ValidationToast/ProgressBar.tsx
  src/components/ValidationToast/ValidationToast.stories.tsx
  src/components/ValidationToast/ValidationToast.tsx
  src/recoil/hookForm/HookForm.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: feat

#72 Fix/#65 review key
  jest.config.js
  package-lock.json
  package.json
  src/components/Review/Review.tsx
Labels: fix

#74 Fix/#66 create class calendar
  src/app/class/create/_components/ClassSchedule/ClassDay/ClassDay.tsx
  src/app/class/create/_components/ClassSchedule/ClassDay/DayByDay.tsx
  src/app/class/create/_components/ClassSchedule/ClassDay/SpecificDate.tsx
  src/app/class/create/_components/ClassSchedule/ClassDay/TimeList.tsx
  src/app/class/create/_components/ClassSchedule/ClassRange/ClassRange.tsx
  src/app/class/create/_components/ClassSchedule/DayOff/DayOff.tsx
  src/components/Calendar/DayOffCalendar.tsx
  src/components/Calendar/InputClassDates.tsx
  src/components/Calendar/RangeCalendar.tsx
  src/components/Calendar/ScheduleCalendar.tsx
  src/components/ScheduleView/ScheduleView.tsx
  src/recoil/ClassSchedule/atoms.ts
  src/styles/calendar.css
  src/types/types.d.ts
  src/utils/specificDateReducer.ts
Labels: fix, feat, refactor
