Repository connection-2023/frontend, pull requests merged in 2023-12, with the labels that each got.

#165 Feat/#164 payment url
  public/icons/copy.svg
  public/icons/svg.ts
  src/app/api/payment/accountInfo/route.ts
  src/app/api/payment/cancel/route.ts
  src/app/api/payment/payInfo/route.ts
  src/app/my/payment-history/_components/PaymentList.tsx
  src/app/my/payment-history/page.tsx
  src/lib/apis/paymentApis.ts
  src/lib/apis/serverApis/paymentsApis.ts
  src/types/payment.d.ts
  src/types/types.d.ts
Labels: feat

#174 Feat/#170 report
  src/app/api/report/lecturer/history/route.ts
  src/app/api/report/lecturer/submit/route.ts
  src/app/api/report/user/history/route.ts
  src/app/api/report/user/submit/route.ts
  src/app/class/[id]/@modal/(...)report/page.tsx
  src/app/class/[id]/_components/ClassReviewSection.tsx
  src/app/class/[id]/_components/OptionButton.tsx
  src/app/class/[id]/page.tsx
  src/app/my/report/ReportModal.tsx
  src/app/my/report/page.tsx
  src/app/report/page.tsx
  src/components/CheckBox/ReportCheckBox.tsx
  src/components/Review/UserReview.tsx
  src/lib/apis/reportApis.ts
  src/types/form.d.ts
  src/types/report.d.ts
Labels: feat, API

#177 Feat/#176 class create
  src/app/class/create/_components/ClassCreate.tsx
  src/app/class/create/_components/ClassSchedule.tsx
  src/app/class/create/_components/ClassSchedule/ClassRange/ClassRange.tsx
  src/app/class/create/_components/ClassSchedule/DayOff/DayOff.tsx
  src/lib/apis/classApi.ts
  src/types/class.d.ts
  src/utils/apiDataProcessor.ts
  src/utils/parseUtils.ts
Labels: fix, feat, refactor

#182 Feat/#112 instructor detail
  src/app/Instructor/[id]/_components/ReviewSection.tsx
  src/app/Instructor/[id]/page.tsx
  src/app/api/class/schedules/route.ts
  src/app/api/post/review/instructor/route.ts
  src/components/ClassPreview/ClassDates.tsx
  src/components/ClassPreview/ClassPreview.tsx
  src/components/Like/Like.tsx
  src/components/Review/Review.tsx
  src/lib/apis/classApis.ts
  src/lib/apis/instructorPostApis.ts
  src/lib/apis/serverApis/instructorPostApis.ts
  src/types/class.d.ts
  src/types/instructor.d.ts
  src/utils/apiDataProcessor.ts
Labels: feat, API

#186 약관동의 API 연결
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/_components/UserConsentForm.tsx
  src/app/(auth)/register/page.tsx
  src/app/@modal/(.)register/page.tsx
  src/app/@modal/(.)upload-profile/page.tsx
  src/app/@modal/(.)welcome/[nickname]/page.tsx
Labels: feat

#189 강사 클래스 관리 페이지 API 부분 연결
  src/app/api/class/edit/route.ts
  src/app/api/class/info/route.ts
  src/app/api/class/myclass/learners/route.ts
  src/app/api/class/myclass/lecturer/route.ts
  src/app/api/class/myclass/registerLists/route.ts
  src/app/class/create/_components/ClassSchedule/DayOff/DayOff.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassOverview.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassTable.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/EditDayOff.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/EditReservationComment.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/EnrollmentModal.tsx
  src/app/mypage/instructor/manage/myclass/[id]/page.tsx
  src/app/mypage/instructor/manage/myclass/_components/ClassDetailView.tsx
  src/app/mypage/instructor/manage/myclass/_components/ClassList.tsx
  src/app/mypage/instructor/manage/myclass/_components/ClassListView.tsx
  src/app/mypage/instructor/manage/myclass/_components/detail/ClassOverview.tsx
  src/app/mypage/instructor/manage/myclass/_components/detail/ClassTable.tsx
  src/app/mypage/instructor/manage/myclass/_components/detail/EditDayOff.tsx
  src/app/mypage/instructor/manage/myclass/page.tsx
  src/components/Button/UniqueButton.tsx
  src/components/Calendar/BasicCalendar.stories.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/components/ClassNotice/Notice.tsx
  src/components/ClassPreview/ClassDates.tsx
  src/components/Filter/DateFilter.tsx
  src/components/UploadImage/CropperModal.tsx
  src/constants/constants.ts
  src/lib/apis/classApis.ts
  src/types/class.d.ts
  src/utils/parseUtils.ts
Labels: API

#193 Feat/#188 pass
  public/icons/pass.svg
  public/icons/svg.ts
  src/app/_components/Sidebar.tsx
  src/app/api/pass/getIssuedPassList/route.ts
  src/app/api/pass/new/route.ts
  src/app/mypage/instructor/coupon-pass/@managementModal/(.)coupon/page.tsx
  src/app/mypage/instructor/coupon-pass/@managementModal/(.)pass/page.tsx
  src/app/mypage/instructor/coupon-pass/@managementModal/default.tsx
  src/app/mypage/instructor/coupon-pass/_components/ClassFilterSelect.tsx
  src/app/mypage/instructor/coupon-pass/_components/CouponView.tsx
  src/app/mypage/instructor/coupon-pass/_components/CreatePass.tsx
  src/app/mypage/instructor/coupon-pass/_components/PassContainer.tsx
  src/app/mypage/instructor/coupon-pass/_components/PassDetail.tsx
  src/app/mypage/instructor/coupon-pass/_components/PassListView.tsx
  src/app/mypage/instructor/coupon-pass/coupon/page.tsx
  src/app/mypage/instructor/coupon-pass/layout.tsx
  src/app/mypage/instructor/coupon-pass/page.tsx
  src/app/mypage/instructor/coupon-pass/pass/page.tsx
  src/app/mypage/instructor/layout.tsx
  src/app/mypage/user/[coupon-pass]/_components/ClassFilterSelectListsUser.tsx
  src/app/mypage/user/[coupon-pass]/_components/ClassFilterSelectUser.tsx
  src/app/mypage/user/[coupon-pass]/_components/CouponView.tsx
  src/app/mypage/user/[coupon-pass]/page.tsx
  src/components/Coupon/Coupon.tsx
  src/components/Coupon/CouponContainer.tsx
  src/components/Pass/AppliedList.tsx
  src/components/Pass/InstructorPass.tsx
  src/components/Pass/PassContainer.tsx
  src/constants/constants.ts
  src/constants/dummy.ts
  src/lib/apis/passApis.ts
  src/lib/apis/serverApis/passApis.ts
  src/types/coupon.d.ts
  src/types/pass.d.ts
  src/utils/useCouponPassHook.ts
Labels: feat, refactor, API

#196 마이페이지 리뷰 관리 구현
  public/icons/bigStar.svg
  public/icons/svg.ts
  src/app/api/review/lecturer/route.ts
  src/app/api/review/new/route.ts
  src/app/api/review/user/route.ts
  src/app/mypage/instructor/review/_components/ClassFilterSelect.tsx
  src/app/mypage/instructor/review/_components/MyReview.tsx
  src/app/mypage/instructor/review/page.tsx
  src/app/mypage/user/review/@writeReviewModal/(.)writeReviewModal/_components/ClassSelect.tsx
  src/app/mypage/user/review/@writeReviewModal/(.)writeReviewModal/_components/WriteReview.tsx
  src/app/mypage/user/review/@writeReviewModal/(.)writeReviewModal/page.tsx
  src/app/mypage/user/review/@writeReviewModal/default.tsx
  src/app/mypage/user/review/_components/MyReview.tsx
  src/app/mypage/user/review/layout.tsx
  src/app/mypage/user/review/page.tsx
  src/app/mypage/user/review/writeReviewModal/page.tsx
  src/components/Review/Rating.tsx
  src/components/Review/ReviewStatistics.tsx
  src/components/Review/UserReview.tsx
  src/lib/apis/reviewApis.ts
  src/lib/apis/serverApis/reviewApis.ts
  src/types/review.d.ts
  src/types/types.d.ts
  src/utils/usePagenation.ts
Labels: feat, API

#197 Feat/#195 modal
  package-lock.json
  package.json
  src/components/Modal/MobileModal.tsx
  src/components/Modal/Modal.tsx
  src/hooks/useBottomSheet.ts
  src/hooks/usePreviousValue.ts
Labels: feat

#198 클래스 수정 페이지 부분 구현
  src/app/class/[id]/edit/_components/EditClassRange.tsx
  src/app/class/[id]/edit/_components/EditDayoff.tsx
  src/app/class/[id]/edit/_components/SideNavbar.tsx
  src/app/class/[id]/edit/page.tsx
  src/lib/apis/classApis.ts
  src/types/class.d.ts
Labels: feat

#199 feat/#170 report
  src/app/mypage/instructor/report/page.tsx
  src/app/mypage/user/report/page.tsx
  src/lib/apis/reportApis.ts
  src/types/report.d.ts
Labels: feat

#202 404 페이지 구현
  public/images/NotFound.png
  src/app/not-found.tsx
Labels: feat
