Repository connection-2023/frontend, pull requests merged in 2024-03, with the labels that each got.

#302 마이페이지 결제내역 조회 리팩토링
  src/app/_components/MypageLinks.tsx
  src/app/_components/Sidebar.tsx
  src/app/mypage/user/payment-history/[orderId]/page.tsx
  src/app/mypage/user/payment-history/_components/EmptyData.tsx
  src/app/mypage/user/payment-history/_components/PaymentList.tsx
  src/app/mypage/user/payment-history/_components/RefundAccountModal.tsx
  src/app/mypage/user/payment-history/_components/RefundList.tsx
  src/app/mypage/user/payment-history/page.tsx
  src/lib/apis/paymentApis.ts
  src/types/types.d.ts
Labels: refactor

#306 수강생 메모 API 연결 및 UI 업데이트
  src/app/mypage/instructor/manage/myclass/[id]/_components/EnrollmentModal.tsx
  src/components/Profile/UserProfileMenu.tsx
Labels: feat

#308 전체 레이아웃 조정
  src/app/_components/ControlOptions.tsx
  src/app/class/[id]/apply/complete/layout.tsx
  src/app/class/[id]/apply/complete/page.tsx
  src/app/class/[id]/apply/page.tsx
  src/app/class/create/[id]/_components/ClassCreateContainer.tsx
  src/app/class/create/drafts/page.tsx
  src/app/class/page.tsx
  src/app/dashboard/layout.tsx
  src/app/error.tsx
  src/app/instructor/page.tsx
  src/app/layout.tsx
  src/app/more/page.tsx
  src/app/mypage/instructor/layout.tsx
  src/app/mypage/user/layout.tsx
  src/app/not-found.tsx
  src/app/receipt/page.tsx
Labels: feat

#309 버튼 호버 스타일 수정 및 bf캐싱 적용
  next.config.js
  src/constants/constants.ts
  tailwind.config.ts
Labels: feat

#312 클래스 관련 기능 수정 및 리팩토링
  src/app/class/[id]/_components/Apply.tsx
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/class/[id]/_components/ClassReviewSection.tsx
  src/lib/apis/classApis.ts
Labels: feat, refactor

#314 로그아웃 버그 수정
  src/app/_components/Header/ProfileMenu.tsx
  src/app/api/auth/logout/route.ts
  src/app/more/UserProfile.tsx
Labels: fix

#317 클래스 일정 관련 컴포넌트 구현 및 API 반환 값 적용
  src/app/class/[id]/_components/Apply.tsx
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/class/[id]/_components/RegularApply.tsx
  src/app/class/[id]/apply/page.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/components/ClassPreview/ClassDates.tsx
  src/components/ScheduleView/RegularScheduleView.tsx
  src/lib/apis/classApis.ts
  src/types/class.d.ts
  src/utils/scheduleDateUtils.ts
  tailwind.config.ts
Labels: feat

#318 결제 승인/결과 조회 로직 분리
  src/app/class/[id]/apply/complete/page.tsx
  src/lib/apis/serverApis/paymentsApis.ts
Labels: refactor

#320 강사 등록 버그 해결
  src/app/api/instructors/register/route.ts
  src/app/instructor/apply/_components/InstructorAuth/Nickname.tsx
  src/app/instructor/apply/_components/InstructorIntroduction.tsx
  src/app/instructor/apply/page.tsx
  src/lib/apis/instructorApi.ts
Labels: fix, feat

#321 클래스 신청 페이지 정기 클래스 컴포넌트 구현
  src/app/class/[id]/_components/RegularApply.tsx
  src/app/class/[id]/_components/apply/RegularApplyList.tsx
  src/app/class/[id]/_components/apply/ReservationItem.tsx
  src/app/class/[id]/apply/_components/ClassApplicationInfo.tsx
  src/app/class/[id]/apply/_components/RegularClassApplicationInfo.tsx
  src/app/class/[id]/apply/page.tsx
  src/components/ClassPreview/ClassDates.tsx
  src/types/class.d.ts
Labels: feat

#323 UI 디자인 피드백 반영
  public/icons/common/button/ban.svg
  public/icons/svg.ts
  src/app/(auth)/_components/SignIn/AuthButtons/AuthButtons.tsx
  src/app/_components/Banner.tsx
  src/app/_components/ControlOptions.tsx
  src/app/_components/Header/HeaderMenu.tsx
  src/app/_components/MobileNav.tsx
  src/app/class/[id]/_components/ClassReviewSection.tsx
  src/app/class/[id]/_components/UserReservation.tsx
  src/app/class/[id]/apply/_components/ReservationInfo.tsx
  src/app/class/[id]/apply/page.tsx
  src/app/class/[id]/page.tsx
  src/app/instructor/[id]/layout.tsx
  src/app/instructor/[id]/page.tsx
  src/app/mypage/instructor/manage/schedule/_components/ToolBar.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/search/_components/search/SearchInput.tsx
  src/components/Button/OptionButtons.tsx
  src/components/Calendar/DayToolBar.tsx
  src/constants/constants.ts
  src/utils/calendarUtils/CalendarCaption.tsx
Labels: feat

#326 결제 페이지 쿠폰 버그 수정 및 api 변환 적용
  src/app/api/payment/pass/route.ts
  src/app/class/[id]/apply/_components/ApplySidebar.tsx
  src/app/class/[id]/apply/_components/Coupon/CouponClient.tsx
  src/app/class/[id]/apply/page.tsx
  src/app/pass/[id]/apply/_components/PaymentForm.tsx
  src/app/pass/[id]/apply/complete/page.tsx
  src/lib/apis/paymentApis.ts
Labels: fix, refactor

#327 정기 클래스 관련 추가 구현 및 리팩토링
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassOverview.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassTable.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassTableList.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/EditDayOff.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/EnrollmentModal.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/RegularClassTable.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_utils/formatSchedule.ts
  src/app/mypage/instructor/manage/myclass/[id]/page.tsx
  src/app/mypage/instructor/manage/myclass/_components/ClassList.tsx
  src/app/mypage/instructor/manage/myclass/page.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/lib/apis/classApis.ts
  src/types/class.d.ts
Labels: feat

#329 검색 키워드 관련 API 연결
  src/app/api/users/delete-keyword/route.ts
  src/app/search/_components/Search.tsx
  src/app/search/_components/search/ListItem.tsx
  src/app/search/_components/search/MyKeyword.tsx
  src/lib/apis/searchApis.ts
  src/lib/apis/serverApis/searchApis.ts
  src/types/types.d.ts
Labels: feat

#331 정기 클래스 최종 날짜 데이터 계산 로직 변경
  src/utils/apiDataProcessor.ts
  src/utils/scheduleDateUtils.ts
Labels: refactor

#333 상세페이지 Nav 리팩토링
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/instructor/[id]/_components/ReviewSection.tsx
  src/components/Nav/Nav.tsx
Labels: refactor

#338 클래스 신청, 패스권 구매 컴포넌트 및 프로세스 통일
  public/icons/class/wavyLine.svg
  public/icons/svg.ts
  public/images/fail.png
  public/images/wavy.png
  src/app/class/[id]/_components/Apply.tsx
  src/app/class/[id]/_components/RegularApply.tsx
  src/app/class/[id]/_components/SelectBox.tsx
  src/app/class/[id]/apply/_components/ApplyClassList.tsx
  src/app/class/[id]/apply/complete/page.tsx
  src/app/class/[id]/apply/loading.tsx
  src/app/class/[id]/apply/page.tsx
  src/app/mypage/user/payment-history/_components/PaymentList.tsx
  src/app/order/@modal/(..)receipt/page.tsx
  src/app/order/@modal/default.tsx
  src/app/order/[type]/[id]/_components/ApplySidebar.tsx
  src/app/order/[type]/[id]/_components/Class/ClassApplicationInfo.tsx
  src/app/order/[type]/[id]/_components/Class/Coupon/CouponClient.tsx
  src/app/order/[type]/[id]/_components/Class/Coupon/CouponContainer.tsx
  src/app/order/[type]/[id]/_components/Class/Coupon/CouponSelect.tsx
  src/app/order/[type]/[id]/_components/Class/Coupon/index.tsx
  src/app/order/[type]/[id]/_components/Class/Pass/PassContainer.tsx
  src/app/order/[type]/[id]/_components/Class/Pass/PassSelect.tsx
  src/app/order/[type]/[id]/_components/Class/Pass/index.tsx
  src/app/order/[type]/[id]/_components/Class/RegularClassApplicationInfo.tsx
  src/app/order/[type]/[id]/_components/Class/index.tsx
  src/app/order/[type]/[id]/_components/Pass/AppliedClassView.tsx
  src/app/order/[type]/[id]/_components/Pass/index.tsx
  src/app/order/[type]/[id]/_components/PaymentType.tsx
  src/app/order/[type]/[id]/_components/ReservationInfo.tsx
  src/app/order/[type]/[id]/loading.tsx
  src/app/order/[type]/[id]/page.tsx
  src/app/order/complete/layout.tsx
  src/app/order/complete/page.tsx
  src/app/order/fail/page.tsx
  src/app/order/layout.tsx
  src/app/pass/[id]/apply/_components/BuyerInfo.tsx
  src/app/pass/[id]/apply/_components/PaymentForm.tsx
  src/app/pass/[id]/apply/complete/page.tsx
  src/app/pass/[id]/apply/page.tsx
  src/components/Apply/RegularApplyList.tsx
  src/components/Apply/ReservationItem.tsx
  src/components/Pass/UserPass.tsx
  src/constants/constants.ts
  src/types/payment.d.ts
Labels: feat, refactor

#340 클래스 진행도 및 진행횟수 로직 변경
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassOverview.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/RegularClassTable.tsx
  src/app/mypage/instructor/manage/myclass/[id]/page.tsx
  src/app/mypage/instructor/manage/myclass/_components/ClassList.tsx
  src/store/classProgressStore.ts
  src/store/index.ts
  src/types/class.d.ts
Labels: feat, refactor

#341 결제내역 조회 패스권 추가 구현 및 페이지네이션 방식 리팩토링
  src/app/mypage/user/payment-history/[orderId]/page.tsx
  src/app/mypage/user/payment-history/_components/PaymentList.tsx
  src/app/mypage/user/payment-history/page.tsx
  src/lib/apis/paymentApis.ts
  src/types/payment.d.ts
  src/types/types.d.ts
Labels: feat, refactor

#343 인기 검색어 및 검색 기록 전체 삭제 API 연결
  src/app/api/users/delete-all-keywords/route.ts
  src/app/search/_components/Search.tsx
  src/app/search/_components/search/ListItem.tsx
  src/app/search/_components/search/MyKeyword.tsx
  src/app/search/_components/search/SearchInput.tsx
  src/constants/constants.ts
  src/constants/dummy.ts
  src/lib/apis/searchApis.ts
  src/lib/apis/serverApis/searchApis.ts
  src/types/types.d.ts
Labels: API
