Repository connection-2023/frontend, pull requests merged in 2024-02, with the labels that each got.

#265 프로덕션 미들웨어 / pass 404 error / 프로필 이미지 타입 기능 추가 및 버그 해결
  src/app/_components/Header/UserStoreInitializer.tsx
  src/app/mypage/instructor/coupon-pass/@managementModal/(.)coupon/page.tsx
  src/app/pass/page.tsx
  src/constants/constants.ts
  src/lib/apis/serverApis/userApi.ts
  src/middleware.ts
  src/store/userStore.ts
  src/types/auth.d.ts
  src/utils/apiDataProcessor.ts
  src/utils/reloadMessage.ts
Labels: fix, feat, refactor

#263 클래스 상세 페이지 버그 수정
  src/app/class/[id]/_components/Apply.tsx
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/class/[id]/_components/apply/ApplyList.tsx
  src/app/class/[id]/_components/apply/ReservationItem.tsx
Labels: fix, feat

#267 대시보드 버그 수정 및 UI 개선
  src/app/dashboard/_components/ResponsiveScheduleView.tsx
  src/app/dashboard/page.tsx
  src/components/Calendar/SingleCalendar.tsx
  src/store/dashboardStore.ts
Labels: fix, feat

#270 프로필 메뉴 공통 컴포넌트로 리팩토링
  src/app/_components/Header/Profile.tsx
  src/app/_components/Sidebar.tsx
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/coupon/[code]/page.tsx
  src/app/dashboard/_components/RecentApply.tsx
  src/app/dashboard/_components/RecentReview.tsx
  src/app/mypage/instructor/coupon-pass/_components/PassDetail.tsx
  src/app/mypage/instructor/manage/approval-pending/_components/ApplicantProfile.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassOverview.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/EnrollmentModal.tsx
  src/app/mypage/user/instructor/_components/BlockedInstructors.tsx
  src/app/mypage/user/myclass/apply/_components/ClassDetailView.tsx
  src/app/mypage/user/myclass/apply/_components/ClassList.tsx
  src/app/notify/page.tsx
  src/components/ClassPreview/ClassPreview.tsx
  src/components/ClassPreview/ResponsiveClassPreview.tsx
  src/components/MyInfo/Info.tsx
  src/components/Profile/InstructorProfileMenu.tsx
  src/components/Profile/ProfileImage.stories.tsx
  src/components/Profile/ProfileImage.tsx
  src/components/Profile/UserProfileMenu.tsx
  src/components/Review/UserReview.tsx
Labels: refactor

#272 루트 에러 페이지 구현
  src/app/error.tsx
Labels: feat

#274 404 페이지 최대 이미지 크기 수정
  src/app/not-found.tsx
Labels: feat

#275 잔버그 수정
  public/icons/common/button/heart.svg
  public/icons/common/button/line-heart.svg
  public/icons/svg.ts
  src/app/(auth)/signin/_components/LoginButtons.tsx
  src/app/_components/Header/HeaderMenu.tsx
  src/app/_components/Header/ProfileMenu.tsx
  src/app/_components/Sidebar.tsx
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/class/[id]/_components/ClassPreview.tsx
  src/app/mypage/user/layout.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Like/Like.tsx
  src/components/Modal/SidebarModal.tsx
  src/components/Nav/Nav.tsx
  src/components/Profile/ProfileImage.tsx
Labels: fix

#279 Github Actions 워크플로우 속도 개선
  .github/workflows/dev_pipeline.yml
  .github/workflows/storybook_pipeline.yml
  .storybook/main.ts
Labels: enhancement

#286 스토리북 작성 및 추가 보완
  .storybook/main.ts
  package-lock.json
  package.json
  src/app/_components/Home/SuggestionClass.tsx
  src/components/Button/ApplyButton.stories.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/CountButton.stories.tsx
  src/components/Button/FilterButton.stories.tsx
  src/components/Button/OptionButton.stories.tsx
  src/components/Button/OptionButtons.tsx
  src/components/Button/ResetButton.stories.tsx
  src/components/Button/Sharing.tsx
  src/components/Button/StatusButton.stories.tsx
  src/components/Button/UniqueButton.stories.tsx
  src/components/Calendar/BasicCalendar.stories.tsx
  src/components/Calendar/RangeCalendar.stories.tsx
  src/components/Calendar/SingleCalendar.stories.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/ClassNotice/Notice.stories.tsx
  src/components/ClassPreview/ClassPreview.stories.tsx
  src/components/ClassPreview/ResponsiveClassPreview.tsx
  src/components/ClassPreview/SuggestionClassPreview.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/InstructorCard/InstructorPreview.stories.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/SidebarModal.stories.tsx
  src/components/Pagination/Pagination.stories.tsx
  src/components/Preview/InstructorPreview.tsx
  src/components/Profile/InstructorProfileMenu.stories.tsx
  src/components/Profile/ProfileImage.stories.tsx
  src/components/Profile/ProfileImage.tsx
  src/components/Profile/UserProfileMenu.stories.tsx
  src/components/Profile/UserProfileMenu.tsx
  src/components/Review/Rating.stories.tsx
  src/components/Review/Review.stories.tsx
  src/components/Review/ReviewStatistics.stories.tsx
  src/components/Review/UserReview.stories.tsx
  src/components/ScheduleView/ScheduleView.stories.tsx
  src/components/Selector/PageSizeSelector.stories.tsx
  src/components/Sharing/Sharing.stories.tsx
  src/components/Spinner/Spinner.stories.tsx
  src/components/UploadImage/UploadImage.stories.tsx
  src/styles/Colors.mdx
Labels: feat

#289 GoogleAnalytics 도입
  package-lock.json
  package.json
  src/app/api/class/detail/route.ts
  src/app/class/@modal/(...)receipt/page.tsx
  src/app/class/@modal/(...)report/page.tsx
  src/app/class/@modal/default.tsx
  src/app/class/[id]/apply/complete/@modal/default.tsx
  src/app/class/[id]/apply/complete/layout.tsx
  src/app/class/[id]/apply/page.tsx
  src/app/class/[id]/layout.tsx
  src/app/class/layout.tsx
  src/app/layout.tsx
  src/components/TextArea/CustomEditor.tsx
Labels: feat

#292 회원 관리 페이지 구현
  public/icons/my/memo.svg
  public/icons/svg.ts
  src/app/api/instructors/memo/route.ts
  src/app/api/instructors/my-member/route.ts
  src/app/mypage/instructor/coupon-pass/_components/PassDetail.tsx
  src/app/mypage/instructor/manage/member/[id]/_components/ClassApplied.tsx
  src/app/mypage/instructor/manage/member/[id]/_components/Member.tsx
  src/app/mypage/instructor/manage/member/[id]/_components/MemberPass.tsx
  src/app/mypage/instructor/manage/member/[id]/_components/PassesView.tsx
  src/app/mypage/instructor/manage/member/[id]/layout.tsx
  src/app/mypage/instructor/manage/member/[id]/page.tsx
  src/app/mypage/instructor/manage/member/_components/ExcelDownload.tsx
  src/app/mypage/instructor/manage/member/_components/FilterNav.tsx
  src/app/mypage/instructor/manage/member/_components/MemberListView.tsx
  src/app/mypage/instructor/manage/member/_components/MemberManage.tsx
  src/app/mypage/instructor/manage/member/layout.tsx
  src/app/mypage/instructor/manage/member/page.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Profile/ProfileImage.tsx
  src/constants/constants.ts
  src/lib/apis/instructorApi.ts
  src/lib/apis/serverApis/instructorPostApis.ts
  src/store/memberStore.ts
  src/styles/globals.css
  src/types/instructor.d.ts
  src/utils/formatDate.ts
Labels: feat, API

#291 클래스 상세페이지 리팩토링 및 추가 구현
  public/icons/class/time.svg
  src/app/class/[id]/_components/Apply.tsx
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/class/[id]/_components/ClassPreview.tsx
  src/app/class/[id]/_components/apply/ApplyList.tsx
  src/app/class/[id]/_components/apply/ReservationItem.tsx
  src/app/class/[id]/apply/_components/ApplySidebar.tsx
  src/app/class/[id]/apply/_components/ClassApplicationInfo.tsx
  src/app/class/[id]/apply/_components/Coupon.tsx
  src/app/class/[id]/apply/_components/ReservationInfo.tsx
  src/app/class/[id]/apply/_lib/applyScheduleUtils.ts
  src/app/class/[id]/apply/complete/page.tsx
  src/app/class/[id]/apply/layout.tsx
  src/app/class/[id]/apply/loading.tsx
  src/app/class/[id]/apply/page.tsx
  src/app/class/[id]/edit/_components/NonEditableSection.tsx
  src/app/class/[id]/edit/page.tsx
  src/app/class/[id]/page.tsx
  src/components/Calendar/SingleCalendar.tsx
  src/components/Loading/ApplyLoading.tsx
  src/components/ScheduleView/FormatCreateSchedule.tsx
  src/components/ScheduleView/FormatSchedule.tsx
  src/components/ScheduleView/ScheduleView.tsx
  src/lib/apis/serverApis/classPostApis.ts
  src/utils/parseUtils.ts
Labels: feat, refactor

#293 대시보드 UI 개선 및 리팩토링
  package-lock.json
  package.json
  src/app/dashboard/_components/DashboardCalendar.tsx
  src/app/dashboard/_components/RecentApply.tsx
  src/app/dashboard/_components/RecentReview.tsx
  src/app/dashboard/_components/ResponsiveScheduleView.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/lib/apis/serverApis/classApi.ts
  src/types/class.d.ts
  src/utils/dateTimeUtils.ts
Labels: package, feat, refactor

#296 강사 수익관리 페이지 API 연동 및 로딩 구현
  public/icons/logo/sns/excel.svg
  src/app/api/income/history/route.ts
  src/app/api/income/recent-account/route.ts
  src/app/api/income/stat/route.ts
  src/app/api/income/total-income/route.ts
  src/app/mypage/instructor/income/_components/AccountInfo.tsx
  src/app/mypage/instructor/income/_components/IncomeDataViewer.tsx
  src/app/mypage/instructor/income/_components/IncomeOverview.tsx
  src/app/mypage/instructor/income/_components/IncomeRange.tsx
  src/app/mypage/instructor/income/_components/IncomeTable.tsx
  src/app/mypage/instructor/income/_components/Loading/IncomeDataViewerLoading.tsx
  src/app/mypage/instructor/income/_components/Loading/IncomeOverviewLoading.tsx
  src/app/mypage/instructor/income/_lib/chartUtils.ts
  src/app/mypage/instructor/income/_lib/initialDate.ts
  src/app/mypage/instructor/income/page.tsx
  src/constants/constants.ts
  src/constants/dummy.ts
  src/lib/apis/incomeApis.ts
  src/types/payment.d.ts
  src/types/types.d.ts
Labels: feat

#300 `Sentry` 패키지 설치 및 적용
  .gitignore
  next.config.js
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/global-error.jsx
Labels: package

#301 클래스 작성 일정 파트 리팩토링
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/class/create/[id]/_components/ClassCreateContainer.tsx
  src/app/class/create/[id]/_components/ClassSchedule.tsx
  src/app/class/create/[id]/_components/ClassSchedule/ClassDay/ClassDay.tsx
  src/app/class/create/[id]/_components/ClassSchedule/ClassDay/DayByDay.tsx
  src/app/class/create/[id]/_components/ClassSchedule/ClassDay/SpecificDate.tsx
  src/app/class/create/[id]/_components/ClassSchedule/ClassDay/TimeList.tsx
  src/app/class/create/[id]/_components/ClassSchedule/DayOff/DayOff.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/components/Calendar/SingleCalendar.tsx
  src/components/ScheduleView/ScheduleView.tsx
  src/store/classScheduleStore.ts
  src/store/index.ts
  src/styles/calendar.css
  src/types/class.d.ts
  src/utils/apiDataProcessor.ts
  src/utils/parseUtils.ts
  src/utils/scheduleDateUtils.ts
  src/utils/specificDateReducer.ts
Labels: refactor
