Repository connection-2023/frontend, pull requests merged in 2024-01, with the labels that each got.

#206 Feat/#76 class plan
  src/app/_components/Sidebar.tsx
  src/app/api/instructors/monthly-schedules/route.ts
  src/app/dashboard/_components/EventList.tsx
  src/app/dashboard/_components/RecentReview.tsx
  src/app/dashboard/_components/ResponsiveScheduleView.tsx
  src/app/dashboard/_components/ScheduleEventModal.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/mypage/instructor/manage/schedule/_components/CalendarDetail.tsx
  src/app/mypage/instructor/manage/schedule/_components/Event.tsx
  src/app/mypage/instructor/manage/schedule/_components/FullCalendar.tsx
  src/app/mypage/instructor/manage/schedule/_components/ResponsiveEventCalendar.tsx
  src/app/mypage/instructor/manage/schedule/page.tsx
  src/components/Calendar/DayCalendar.tsx
  src/components/Calendar/DayToolBar.tsx
  src/components/Calendar/SingleCalendar.tsx
  src/constants/constants.ts
  src/lib/apis/instructorApi.ts
  src/styles/calendar.css
  src/styles/fullCalendar.css
  src/types/class.d.ts
  src/types/review.d.ts
  src/types/types.d.ts
  src/utils/fullCalendarUtils.ts
Labels: feat

#212 클래스 신청 페이지 변경된 디자인 적용
  package-lock.json
  package.json
  src/app/class/[id]/apply/_components/AccountInfo.tsx
  src/app/class/[id]/apply/_components/ApplyClassList.tsx
  src/app/class/[id]/apply/_components/ApplySidebar.tsx
  src/app/class/[id]/apply/_components/PaymentMethod.tsx
  src/app/class/[id]/apply/_components/PaymentType.tsx
  src/app/class/[id]/apply/page.tsx
  src/constants/constants.ts
  src/store/paymentStore.ts
Labels: feat

#215 강사 마이페이지-승인대기/환불요청 탭 UI 구현
  public/icons/check-circle.svg
  public/icons/svg.ts
  src/app/_components/Header/HeaderMenu.tsx
  src/app/_components/Sidebar.tsx
  src/app/mypage/instructor/layout.tsx
  src/app/mypage/instructor/manage/approval-pending/_components/ClassList.tsx
  src/app/mypage/instructor/manage/approval-pending/_components/DeclineModal.tsx
  src/app/mypage/instructor/manage/approval-pending/_components/PaymentInfoModal.tsx
  src/app/mypage/instructor/manage/approval-pending/_components/PendingList.tsx
  src/app/mypage/instructor/manage/approval-pending/page.tsx
  src/app/mypage/instructor/refund/_components/ApplyDetailModal.tsx
  src/app/mypage/instructor/refund/_components/DeclineModal.tsx
  src/app/mypage/instructor/refund/_components/RefundList.tsx
  src/app/mypage/instructor/refund/page.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Modal/SidebarModal.tsx
Labels: feat

#218 유저 마이페이지 환불 내역 UI 구현
  src/app/mypage/user/payment-history/_components/RefundAccountModal.tsx
  src/app/mypage/user/payment-history/_components/RefundList.tsx
  src/app/mypage/user/payment-history/page.tsx
Labels: feat

#210 Feat/#190 edit class
  public/icons/clear.svg
  src/app/class/[id]/edit/_components/AddSchedules.tsx
  src/app/class/[id]/edit/_components/EditDayoff.tsx
  src/app/class/[id]/edit/_components/SideNavbar.tsx
  src/app/class/[id]/edit/_components/TimeList.tsx
  src/app/class/[id]/edit/page.tsx
  src/app/class/create/_components/ClassLocation.tsx
  src/app/class/create/_components/ClassSchedule/ClassDay/TimeList.tsx
  src/components/Calendar/SingleCalendar.tsx
  src/components/TextArea/CustomEditor.tsx
  src/components/TextArea/TextAreaSection.tsx
  src/components/ValidationMessage/ValidationMessage.tsx
  src/lib/apis/classApis.ts
  src/types/class.d.ts
  src/utils/editSpecificDateReducer.ts
  src/utils/parseUtils.ts
  src/utils/sanitizeHtmlString.ts
Labels: feat

#233 강사 수정 페이지 & 강사 인증 페이지 반응형 작업
  package-lock.json
  package.json
  src/app/Instructor/[id]/edit/_components/EditInstructor.tsx
  src/app/Instructor/[id]/edit/page.tsx
  src/app/Instructor/[id]/page.tsx
  src/app/Instructor/apply/_components/InstructorAuth.tsx
  src/app/Instructor/apply/_components/InstructorAuth/AccountList.tsx
  src/app/Instructor/apply/_components/InstructorAuth/Email.tsx
  src/app/Instructor/apply/_components/InstructorAuth/Label.tsx
  src/app/Instructor/apply/_components/InstructorAuth/Nickname.tsx
  src/app/Instructor/apply/_components/InstructorAuth/PhoneNumber.tsx
  src/app/Instructor/apply/_components/InstructorIntroduction.tsx
  src/app/Instructor/apply/layout.tsx
  src/app/Instructor/apply/page.tsx
  src/app/_components/Header/ProfileMenu.tsx
  src/app/api/instructors/update/route.ts
  src/app/class/[id]/_components/DiscountCouponBanner.tsx
  src/app/class/[id]/page.tsx
  src/app/class/create/_components/ClassExplanation.tsx
  src/app/coupon/[code]/_components/Download.tsx
  src/components/Button/Button.tsx
  src/components/Button/OptionButtons.tsx
  src/components/Coupon/DownloadCoupon.tsx
  src/components/GenreCheckboxGroup/GenreList.tsx
  src/components/GenreCheckboxGroup/GenreListAddition.tsx
  src/components/Modal/MobileModal.tsx
  src/components/SelectLocation/CityList.tsx
  src/components/SelectLocation/WardList.tsx
  src/components/TextArea/CustomEditor.tsx
  src/components/UploadImage/CropperModal.tsx
  src/components/UploadImage/UploadImage.test.tsx
  src/components/UploadImage/UploadImage.tsx
  src/constants/constants.ts
  src/lib/apis/instructorPostApis.ts
  src/lib/apis/serverApis/couponApis.ts
  src/lib/apis/serverApis/instructorPostApis.ts
  src/recoil/Create/atoms.ts
  src/recoil/RecoilProvider.tsx
  src/types/coupon.d.ts
  src/types/instructor.d.ts
  src/utils/apiDataProcessor.ts
  src/utils/calculateMaxDiscount.ts
Labels: feat, API

#235 refactor(#229): 도메인 환경 변수로 변경
  src/app/(auth)/signin/_components/NaverAuth.tsx
  src/app/class/create/address/page.tsx
  src/components/Coupon/Coupon.tsx
  src/components/Sharing/Sharing.tsx
  src/constants/constants.ts
  src/lib/apis/classApi.ts
  src/lib/apis/classApis.ts
  src/lib/apis/couponApis.ts
  src/lib/apis/imageApi.ts
  src/lib/apis/instructorApi.ts
  src/lib/apis/instructorLikesBlockApis.ts
  src/lib/apis/instructorPostApis.ts
  src/lib/apis/passApis.ts
  src/lib/apis/paymentApis.ts
  src/lib/apis/reportApis.ts
  src/lib/apis/reviewApis.ts
  src/lib/apis/searchApis.ts
  src/lib/apis/userApi.ts
Labels: refactor

#239 좋아요 버그, 유저 강사 전환 버그, 메인페이지 캐러셀 수정
  src/app/Instructor/_components/InstructorListView.tsx
  src/app/Instructor/_components/UserLikesInstructorInitializer.tsx
  src/app/Instructor/page.tsx
  src/app/_components/CarouselTemplate.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/UserStoreInitializer.tsx
  src/app/_components/Home/BestClass.tsx
  src/app/_components/Home/BestInstructor.tsx
  src/app/_components/Home/Loading/BestClassLoading.tsx
  src/app/class/[id]/page.tsx
  src/app/class/_components/BestClasses.tsx
  src/app/class/_components/ClassListView.tsx
  src/app/class/_components/UserLikesClassInitializer.tsx
  src/app/class/create/_components/ClassPrice/CouponCreator.tsx
  src/app/class/page.tsx
  src/app/layout.tsx
  src/app/mypage/instructor/coupon-pass/@managementModal/(.)coupon/page.tsx
  src/app/mypage/instructor/coupon-pass/@managementModal/(.)pass/page.tsx
  src/app/page.tsx
  src/app/search/_components/UserLikesInitializer.tsx
  src/components/ClassPreview/ClassPreview.tsx
  src/components/InstructorCard/InstructorCard.tsx
  src/components/Like/Like.tsx
  src/components/Loading/ClassPreviewLoading.tsx
  src/components/Loading/Spinner.tsx
  src/hooks/useIntersect.ts
  src/lib/apis/couponApis.ts
  src/lib/apis/passApis.ts
  src/lib/apis/serverApis/userApi.ts
  src/middleware.ts
  src/types/class.d.ts
Labels: fix, feat, refactor

#241 프로필 메뉴 경로 변경 및 토스트 메세지 로딩 처리
  public/icons/common/chat.svg
  src/app/(auth)/@modal/(.)upload-profile/page.tsx
  src/app/(auth)/signin/_components/LoginButtons.tsx
  src/app/(auth)/upload-profile/page.tsx
  src/app/_components/Footer.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/HeaderMenu.tsx
  src/app/_components/Header/ProfileMenu.tsx
  src/app/_components/Header/UserProfileLinks.tsx
  src/app/_components/Home/BestClass.tsx
  src/app/page.tsx
Labels: feat, refactor

#249 에러 페이지 구현
  public/images/ErrorImg.webp
  src/app/_components/Error.tsx
  src/app/error/page.tsx
Labels: feat

#252 프로덕션 오류 해결
  src/app/_components/Home/RecentClass.tsx
  src/lib/apis/classApi.ts
  src/lib/apis/classApis.ts
  src/lib/apis/couponApis.ts
  src/lib/apis/imageApi.ts
  src/lib/apis/instructorApi.ts
  src/lib/apis/instructorLikesBlockApis.ts
  src/lib/apis/instructorPostApis.ts
  src/lib/apis/passApis.ts
  src/lib/apis/paymentApis.ts
  src/lib/apis/reportApis.ts
  src/lib/apis/reviewApis.ts
  src/lib/apis/searchApis.ts
  src/lib/apis/serverApis/classPostApis.ts
  src/lib/apis/userApi.ts
Labels: fix, refactor

#254 클래스 프리뷰 컴포넌트 클릭 이벤트 추가
  src/app/instructor/[id]/page.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/ClassPreview/ClassPreview.stories.tsx
  src/components/ClassPreview/ClassPreview.tsx
  src/components/ClassPreview/ResponsiveClassPreview.tsx
  src/components/Like/Like.tsx
  src/types/class.d.ts
  src/utils/apiDataProcessor.ts
Labels: feat

#256 서버 상태 관리 로직 해제
  src/app/(auth)/signin/_components/LoginButtons.tsx
  src/app/_components/Header/Header.tsx
  src/app/_components/Header/HeaderMenu.tsx
  src/app/_components/Header/Profile.tsx
  src/app/_components/Header/UserProfileLinks.tsx
  src/app/_components/Home/BestClass.tsx
  src/app/_components/Home/BestInstructor.tsx
  src/app/class/[id]/_components/ClassPreview.tsx
  src/app/class/_components/ClassListView.tsx
  src/app/coupon/[code]/_components/Download.tsx
  src/app/instructor/[id]/edit/_components/IdAccessChecker.tsx
  src/app/layout.tsx
  src/app/search/_components/Results.tsx
  src/components/MyInfo/UpdateModal/UpdateList/EmailUpdate.tsx
  src/components/MyInfo/UpdateModal/UpdateList/PhoneNumberUpdate.tsx
Labels: refactor

#257 [강사] 클래스 관리 페이지 수강생 상세 모달 구현 및 수강생 목록 조회 리팩토링
  src/app/api/class/myclass/lecturer/route.ts
  src/app/api/class/myclass/schedule-learners/route.ts
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassOverview.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassTable.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/EnrollmentModal.tsx
  src/app/mypage/instructor/manage/myclass/[id]/page.tsx
  src/app/mypage/instructor/manage/myclass/page.tsx
  src/constants/dummy.ts
  src/lib/apis/classApis.ts
  src/types/class.d.ts
Labels: feat, refactor, API

#260 로그아웃 토큰 버그 수정
  src/app/api/auth/logout/route.ts
  src/lib/apis/userApi.ts
  src/middleware.ts
Labels: fix, feat
