Repository connection-2023/frontend, pull requests merged in 2024-04, with the labels that each got.

#347 지도 기능 추가 및 리팩토링
  src/app/_components/SocketInitializer.tsx
  src/app/api/map/address/route.ts
  src/app/api/map/point/route.ts
  src/app/api/map/polyline/route.ts
  src/app/class/[id]/_components/Apply.tsx
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/class/[id]/_components/ClassPreview.tsx
  src/app/class/create/[id]/_components/ClassLocation/ConfirmedLocation.tsx
  src/app/layout.tsx
  src/app/mypage/user/myclass/apply/[id]/_components/ClassLocation.tsx
  src/components/Map/AddressMap.tsx
  src/components/Map/AreaHighlightMap.tsx
  src/components/Map/ErrorMap.tsx
  src/components/Map/Map.stories.tsx
  src/components/Map/Map.test.tsx
  src/components/Map/Map.tsx
  src/constants/administrativeDistrict.ts
  src/constants/constants.ts
  src/lib/apis/searchAddress.ts
  src/lib/provider/NaverMapsProviders.tsx
  src/styles/mapInfowindow.css
  src/types/address.d.ts
  src/types/class.d.ts
  src/utils/apiDataProcessor.ts
Labels: feat, refactor

#349 UI 개선 및 메인 렌더링 버그 수정
  src/app/layout.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/components/ClassPreview/ClassDates.tsx
  src/utils/calendarUtils/BigCalendarToolBar.tsx
  src/utils/scheduleDateUtils.ts
  tailwind.config.ts
Labels: fix, feat

#348 클래스 수정 정기 클래스 추가 구현 및 리팩토링
  src/app/class/[id]/edit/_components/EditClassRange.tsx
  src/app/class/[id]/edit/_components/IntroSection.tsx
  src/app/class/[id]/edit/_components/Loading.tsx
  src/app/class/[id]/edit/_components/PriceSection.tsx
  src/app/class/[id]/edit/_components/SideNavbar.tsx
  src/app/class/[id]/edit/_components/plan/EditClassRange.tsx
  src/app/class/[id]/edit/_components/plan/EditDayoff.tsx
  src/app/class/[id]/edit/_components/plan/ScheduleViewer.tsx
  src/app/class/[id]/edit/_components/plan/index.tsx
  src/app/class/[id]/edit/_components/plan/schedule/AddSchedules.tsx
  src/app/class/[id]/edit/_components/plan/schedule/DayClass.tsx
  src/app/class/[id]/edit/_components/plan/schedule/TimeList.tsx
  src/app/class/[id]/edit/_components/plan/schedule/index.tsx
  src/app/class/[id]/edit/_lib/addScheduleUtils.ts
  src/app/class/[id]/edit/_lib/editScheduleUtils.ts
  src/app/class/[id]/edit/layout.tsx
  src/app/class/[id]/edit/loading.tsx
  src/app/class/[id]/edit/page.tsx
  src/components/Calendar/BasicCalendar.tsx
  src/components/Calendar/RangeCalendar.tsx
  src/lib/apis/classApis.ts
  src/store/classScheduleStore.ts
  src/types/class.d.ts
  src/utils/parseUtils.ts
  src/utils/scheduleDateUtils.ts
Labels: feat, refactor

#351 캐러셀 touch Scroll(스와이프) 기능 추가 및 리팩토링
  package-lock.json
  package.json
  src/app/_components/CarouselTemplate.tsx
  src/app/_components/Header/UserStoreInitializer.tsx
  src/app/_components/Home/BestClass.tsx
  src/app/_components/Home/BestInstructor.tsx
  src/app/_components/Home/Loading/BestClassLoading.tsx
  src/app/_components/Home/Loading/BestInstructorLoading.tsx
  src/app/class/[id]/_components/ClassPreview.tsx
  src/app/class/_components/BestClasses.tsx
  src/app/instructor/[id]/_components/ClassList.tsx
  src/app/instructor/[id]/_components/InstructorCarousel.tsx
  src/app/instructor/[id]/page.tsx
  src/app/instructor/_components/BestInstructors.tsx
  src/app/layout.tsx
  src/app/mypage/instructor/manage/member/[id]/_components/MemberPass.tsx
  src/app/mypage/instructor/manage/member/[id]/_components/PassesView.tsx
  src/app/mypage/user/[coupon-pass]/_components/PassView.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/Carousel.test.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Carousel/CarouselContainer.tsx
  src/components/ClassPreview/ClassPreview.tsx
  src/components/ClassPreview/ResponsiveClassPreview.tsx
  src/components/InstructorCard/ImagesViewer.tsx
  src/components/InstructorCard/InstructorCard.tsx
  src/store/userStore.ts
  src/types/cariusel.d.ts
  src/types/class.d.ts
Labels: feat, refactor

#358 fix(#357): vworld 세분화 된 주소 안나오는 버그 해결
  src/app/api/map/polyline/route.ts
  src/components/Map/AreaHighlightMap.tsx
Labels: fix

#353 강사 프로필 페이지 기능 추가 및 리팩토링
  src/app/class/[id]/_components/ClassDetail.tsx
  src/app/class/[id]/_components/ReadMore.tsx
  src/app/instructor/[id]/_components/ClassSection.tsx
  src/app/instructor/[id]/_components/ErrorContainer.tsx
  src/app/instructor/[id]/_components/PassSection.tsx
  src/app/instructor/[id]/_components/ProfileSection.tsx
  src/app/instructor/[id]/_components/loading/ClassSectionLoading.tsx
  src/app/instructor/[id]/_components/loading/PassSectionLoading.tsx
  src/app/instructor/[id]/_components/loading/ProfileSectionLoading.tsx
  src/app/instructor/[id]/page.tsx
  src/components/Nav/Nav.tsx
  src/components/Pass/PassLoading.tsx
  src/components/Pass/UserPass.tsx
  src/constants/constants.ts
  src/lib/apis/serverApis/instructorPostApis.ts
  src/lib/apis/serverApis/passApis.ts
  src/types/class.d.ts
  src/types/pass.d.ts
  src/utils/apiDataProcessor.ts
Labels: feat, refactor

#362 랜딩 페이지 구현
  .storybook/main.ts
  public/icons/common/arrow/doubleRight.svg
  public/icons/landing/click.svg
  public/icons/landing/toggle-triangle.svg
  public/icons/svg.ts
  public/images/landing/instructor/manage.png
  public/images/landing/instructor/pass.png
  public/images/landing/instructor/recruit.png
  public/images/landing/instructor/register.png
  public/images/landing/landing_bg_lg.png
  public/images/landing/landing_bg_md.png
  public/images/landing/landing_bg_sm.png
  public/images/landing/learner/apply.png
  public/images/landing/learner/detail.png
  public/images/landing/learner/search.png
  src/app/(auth)/_components/Register/Welcome.tsx
  src/app/about/_components/Instructor/ClassInfo.tsx
  src/app/about/_components/Instructor/RecruitInfo.tsx
  src/app/about/_components/Instructor/index.tsx
  src/app/about/_components/Learner/ApplyClass.tsx
  src/app/about/_components/Learner/FindClass.tsx
  src/app/about/_components/Learner/index.tsx
  src/app/about/_utils/animationUtils.ts
  src/app/about/_utils/style.ts
  src/app/about/page.tsx
  src/app/mypage/instructor/income/_components/PaymentRange.tsx
  src/components/Modal/SidebarModal.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: feat

#363 알림 기능 구현
  src/app/_components/Header/NotificationIndicator.tsx
  src/app/_components/Header/NotificationList.tsx
  src/app/_components/Header/Previews/ChatPreviews.tsx
  src/app/_components/Header/Previews/NotificationsPreviews.tsx
  src/app/_components/Header/Previews/PreviewsContainer.tsx
  src/app/_components/Header/Profile.tsx
  src/app/_components/Header/UserProfileLinks.tsx
  src/app/_components/SocketInitializer.tsx
  src/app/api/notifications/delete/route.ts
  src/app/api/notifications/get-notifications/route.ts
  src/app/api/notifications/read/route.ts
  src/app/api/notifications/send-notifications/route.ts
  src/app/api/notifications/unread-count/route.ts
  src/app/layout.tsx
  src/app/mypage/instructor/manage/member/_components/MemberListView.tsx
  src/app/mypage/instructor/manage/member/_components/MemberManage.tsx
  src/app/mypage/instructor/manage/member/page.tsx
  src/app/mypage/instructor/manage/myclass/[id]/_components/ClassOverview.tsx
  src/app/mypage/instructor/manage/review/page.tsx
  src/app/mypage/user/[coupon-pass]/page.tsx
  src/app/mypage/user/myclass/review/page.tsx
  src/app/notifications/_components/NotificationItem.tsx
  src/app/notifications/_components/NotificationList.tsx
  src/app/notifications/_components/NotificationsSection.tsx
  src/app/notifications/_components/Profile.tsx
  src/app/notifications/_components/loading/NotificationDeleteLoading.tsx
  src/app/notifications/_components/loading/NotificationLoading.tsx
  src/app/notifications/_components/loading/NotificationsSectionLoading.tsx
  src/app/notifications/page.tsx
  src/components/Coupon/Coupon.tsx
  src/components/Modal/ModalContent.tsx
  src/components/uis/Loading/SendNotificationsLoading.tsx
  src/components/uis/NotificationSenderModal.tsx
  src/components/uis/ReviewSection/ReviewList.tsx
  src/components/uis/ReviewSection/ReviewSection.tsx
  src/constants/constants.ts
  src/hooks/useReadNotification.ts
  src/lib/apis/notifications.ts
  src/lib/apis/serverApis/instructorPostApis.ts
  src/lib/apis/serverApis/notifications.ts
  src/store/notificationsStore.ts
  src/types/instructor.d.ts
  src/types/notifications.d.ts
  src/utils/dateTimeUtils.ts
  src/utils/getInstructorCouponPassInfo.ts
  src/utils/notificationUtils.ts
Labels: feat, API
